defmodule Fluid.Repo.Migrations.AllocationsPool do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pools) do
      add :volume, :bigint, default: 0
    end
  end

  def down do
    alter table(:pools) do
      remove :volume
    end
  end
end