defmodule Fluid.Repo.Migrations.PoolRank do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pools) do
      modify :pool_rank, :bigint, default: 1
    end
  end

  def down do
    alter table(:pools) do
      modify :pool_rank, :bigint, default: nil
    end
  end
end