defmodule Fluid.Repo.Migrations.AllocationsPoolTotalCapacity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pools) do
      add :total_capacity, :bigint
    end
  end

  def down do
    alter table(:pools) do
      remove :total_capacity
    end
  end
end