defmodule Fluid.Repo.Migrations.UpdateTagInConnection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :user_defined_tag, :text
    end
  end

  def down do
    alter table(:tags) do
      remove :user_defined_tag
    end
  end
end