defmodule Fluid.Repo.Migrations.FloatVals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tanks) do
      modify :volume, :float, default: 0.0
      modify :total_capacity, :float
    end

    alter table(:pools) do
      modify :total_capacity, :float
      modify :volume, :float, default: 0.0
    end
  end

  def down do
    alter table(:pools) do
      modify :volume, :bigint, default: 0
      modify :total_capacity, :bigint
    end

    alter table(:tanks) do
      modify :total_capacity, :bigint
      modify :volume, :bigint, default: 0
    end
  end
end