defmodule Fluid.Repo.Migrations.UpdateTanksAllocation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tanks) do
      add :total_capacity, :bigint
      add :volume, :bigint, default: 0
      add :applicable_capacity, :bigint
    end
  end

  def down do
    alter table(:tanks) do
      remove :applicable_capacity
      remove :volume
      remove :total_capacity
    end
  end
end