defmodule Fluid.Repo.Migrations.Allocations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:allocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :volume, :text
      add :stage, :text, default: ""

      add :tag_id,
          references(:tags,
            column: :id,
            name: "allocations_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:allocations, "allocations_tag_id_fkey")

    drop table(:allocations)
  end
end